import type { StylesConfig } from "react-select";

import type { SelectOption } from "./types";

export const PIPELINE_PRESET_OPERATOR_IDS = [
  "camera.source",
  "core.schedule_gate",
  "camera.motion_gate",
  "core.lifecycle_from_boolean",
  "core.fps_reducer",
  "camera.image_crop",
  "vision.object_tracking_yolo",
  "vision.object_detection_yolo",
  "core.category_gate",
  "core.filter",
  "camera.object_segmentation",
  "camera.camera_mapping",
  "camera.area_restriction",
  "camera.velocity_estimation",
  "camera.best_frame_selector",
  "camera.image_adjust",
  "camera.image_resize",
  "core.throttle",
  "core.debounce",
  "core.debug",
  "core.store_images",
  "core.notify",
];

export const NODE_ID_RE = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;

export const OPERATOR_FRIENDLY_NAMES: Record<string, string> = {
  "core.schedule_gate": "Schedule gate",
  "camera.source": "Camera source",
  "camera.motion_gate": "Motion detection gate",
  "core.lifecycle_from_boolean": "Lifecycle from boolean",
  "core.fps_reducer": "FPS reducer",
  "camera.image_crop": "Crop frame",
  "camera.image_adjust": "Image adjust",
  "vision.object_tracking_yolo": "YOLO tracking",
  "vision.object_detection_yolo": "YOLO detection",
  "core.category_gate": "Category gate",
  "core.filter": "Filter",
  "camera.object_segmentation": "Object segmentation",
  "camera.camera_mapping": "Camera mapping",
  "camera.area_restriction": "Area restriction",
  "camera.velocity_estimation": "Velocity estimation",
  "camera.best_frame_selector": "Best frame selector",
  "camera.image_resize": "Resize images",
  "core.throttle": "Throttle",
  "core.debounce": "Debounce",
  "core.debug": "Debug",
  "core.store_images": "Store images",
  "core.notify": "Notification",
};

export const pipelinesReactSelectStyles: StylesConfig<SelectOption, boolean> = {
  container: (base) => ({ ...base }),
  control: (base, state) => ({
    ...base,
    minHeight: 34,
    borderRadius: 10,
    border: `1px solid ${state.isFocused ? "rgba(251,191,36,0.38)" : "rgba(255,255,255,0.12)"}`,
    backgroundColor: "rgba(15, 23, 48, 0.85)",
    boxShadow: state.isFocused ? "0 0 0 1px rgba(251,191,36,0.22)" : "none",
    cursor: "text",
  }),
  menu: (base) => ({
    ...base,
    backgroundColor: "rgba(12, 18, 37, 0.98)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 12,
    overflow: "hidden",
    boxShadow: "0 22px 70px rgba(0, 0, 0, 0.60)",
    zIndex: 50,
  }),
  option: (base, state) => ({
    ...base,
    backgroundColor: state.isSelected
      ? "rgba(251, 191, 36, 0.16)"
      : state.isFocused
        ? "rgba(255, 255, 255, 0.06)"
        : "transparent",
    color: "rgba(230,232,242,0.96)",
    cursor: "pointer",
  }),
  multiValue: (base) => ({
    ...base,
    backgroundColor: "rgba(251, 191, 36, 0.14)",
    border: "1px solid rgba(251, 191, 36, 0.22)",
    borderRadius: 999,
  }),
  multiValueLabel: (base) => ({ ...base, color: "rgba(255, 244, 210, 0.95)", fontWeight: 650 }),
  multiValueRemove: (base) => ({ ...base, color: "rgba(255, 244, 210, 0.85)" }),
  input: (base) => ({ ...base, color: "rgba(230,232,242,0.96)" }),
  placeholder: (base) => ({ ...base, color: "rgba(160,167,189,0.85)" }),
  singleValue: (base) => ({ ...base, color: "rgba(230,232,242,0.96)" }),
  indicatorSeparator: (base) => ({ ...base, backgroundColor: "rgba(255,255,255,0.10)" }),
  dropdownIndicator: (base) => ({ ...base, color: "rgba(160,167,189,0.9)" }),
  clearIndicator: (base) => ({ ...base, color: "rgba(160,167,189,0.9)" }),
};

const YOLO_CATEGORY_VALUES = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
];

export const YOLO_CATEGORY_OPTIONS: SelectOption[] = YOLO_CATEGORY_VALUES.map((value) => ({ value, label: value }));

export const ARTIFACT_SUGGESTIONS: SelectOption[] = [
  { value: "frame_original", label: "Full frame" },
  { value: "frame_cropped", label: "Cropped frame" },
  { value: "frame_adjusted", label: "Adjusted frame" },
  { value: "best_frame", label: "Best frame" },
  { value: "segmented", label: "Segmented" },
  { value: "face", label: "Face" },
  { value: "pose", label: "Pose" },
];

export const SCHEDULE_WEEKDAY_OPTIONS: SelectOption[] = [
  { value: "mon", label: "Mon" },
  { value: "tue", label: "Tue" },
  { value: "wed", label: "Wed" },
  { value: "thu", label: "Thu" },
  { value: "fri", label: "Fri" },
  { value: "sat", label: "Sat" },
  { value: "sun", label: "Sun" },
];

export const HUMANIZE_ACRONYMS: Record<string, string> = {
  id: "ID",
  fps: "FPS",
  rtsp: "RTSP",
  url: "URL",
  jpeg: "JPEG",
  png: "PNG",
  yolo: "YOLO",
  api: "API",
  ui: "UI",
  sse: "SSE",
  ts: "TS",
};
