import type { StylesConfig } from "react-select";

import type { SelectOption } from "./types";

export const PIPELINE_PRESET_OPERATOR_IDS = [
  "camera.source",
  "core.schedule_gate",
  "camera.motion_gate",
  "core.lifecycle_from_boolean",
  "core.fps_reducer",
  "camera.image_crop",
  "camera.image_perspective_crop",
  "vision.object_tracking_yolo",
  "vision.object_detection_yolo",
  "core.category_gate",
  "core.filter",
  "camera.object_segmentation",
  "camera.camera_mapping",
  "camera.area_restriction",
  "camera.velocity_estimation",
  "camera.best_frame_selector",
  "camera.image_adjust",
  "camera.image_resize",
  "core.throttle",
  "core.velocity_throttle",
  "core.debounce",
  "core.debug",
  "core.store_images",
  "core.notify",
  "stream.write",
];

export const NODE_ID_RE = /^[A-Za-z_][A-Za-z0-9_]{0,63}$/;

export const OPERATOR_FRIENDLY_NAMES: Record<string, string> = {
  "core.schedule_gate": "Schedule gate",
  "camera.source": "Camera source",
  "camera.motion_gate": "Motion detection gate",
  "core.lifecycle_from_boolean": "Lifecycle from boolean",
  "core.fps_reducer": "FPS reducer",
  "camera.image_crop": "Crop frame",
  "camera.image_perspective_crop": "Perspective crop",
  "camera.image_adjust": "Image adjust",
  "vision.object_tracking_yolo": "YOLO tracking",
  "vision.object_detection_yolo": "YOLO detection",
  "core.category_gate": "Category gate",
  "core.filter": "Filter",
  "camera.object_segmentation": "Object segmentation",
  "camera.camera_mapping": "Camera mapping",
  "camera.area_restriction": "Area restriction",
  "camera.velocity_estimation": "Velocity estimation",
  "camera.best_frame_selector": "Best frame selector",
  "camera.image_resize": "Resize images",
  "core.throttle": "Throttle",
  "core.velocity_throttle": "Velocity-aware throttle",
  "core.debounce": "Debounce",
  "core.debug": "Debug",
  "core.store_images": "Store images",
  "core.notify": "Notification",
  "stream.write": "Transmit stream",
};

export const pipelinesReactSelectStyles: StylesConfig<SelectOption, boolean> = {
  container: (base) => ({ ...base }),
  control: (base, state) => ({
    ...base,
    minHeight: 40,
    borderRadius: "var(--radius-control)",
    border: `1px solid ${state.isFocused ? "var(--color-accent-border)" : "var(--color-border-subtle)"}`,
    backgroundColor: "var(--color-surface-frost)",
    boxShadow: state.isFocused
      ? "0 0 0 2px var(--color-focus-ring-inner), 0 0 0 4px var(--color-focus-ring-outer)"
      : "inset 0 1px 0 color-mix(in srgb, var(--color-surface-solid) 28%, transparent)",
    cursor: "text",
    backdropFilter: "blur(var(--frost-blur-small)) saturate(var(--frost-saturate)) brightness(var(--frost-brightness))",
    WebkitBackdropFilter: "blur(var(--frost-blur-small)) saturate(var(--frost-saturate)) brightness(var(--frost-brightness))",
    transition: "border-color var(--motion-medium) var(--ease-standard), box-shadow var(--motion-medium) var(--ease-standard)",
  }),
  menu: (base) => ({
    ...base,
    backgroundColor: "var(--color-surface-frost-strong)",
    border: "1px solid var(--color-border-subtle)",
    borderRadius: "var(--radius-panel)",
    overflow: "hidden",
    boxShadow: "var(--shadow-elevation-3)",
    backdropFilter: "blur(var(--frost-blur-large)) saturate(var(--frost-saturate)) brightness(var(--frost-brightness))",
    WebkitBackdropFilter: "blur(var(--frost-blur-large)) saturate(var(--frost-saturate)) brightness(var(--frost-brightness))",
    zIndex: 50,
  }),
  menuList: (base) => ({
    ...base,
    paddingTop: 4,
    paddingBottom: 4,
  }),
  option: (base, state) => ({
    ...base,
    padding: "10px 12px",
    backgroundColor: "transparent",
    background: state.isSelected
      ? "linear-gradient(135deg, var(--color-accent-background-strong), var(--color-accent-background-strong-2))"
      : state.isFocused
        ? "linear-gradient(135deg, var(--color-accent-background-soft), var(--color-accent-background-soft-2))"
        : "transparent",
    color: "var(--color-text-primary)",
    cursor: "pointer",
    borderBottom: "1px solid color-mix(in srgb, var(--color-border-subtle) 35%, transparent)",
  }),
  multiValue: (base) => ({
    ...base,
    backgroundColor: "transparent",
    background: "linear-gradient(135deg, var(--color-accent-background-soft), var(--color-accent-background-soft-2))",
    border: "1px solid var(--color-accent-border)",
    borderRadius: "var(--radius-pill)",
  }),
  multiValueLabel: (base) => ({ ...base, color: "var(--color-text-primary)", fontWeight: 650 }),
  multiValueRemove: (base, state) => ({
    ...base,
    color: "var(--color-text-muted)",
    backgroundColor: state.isFocused ? "var(--color-accent-background-soft)" : "transparent",
  }),
  input: (base) => ({ ...base, color: "var(--color-text-primary)" }),
  placeholder: (base) => ({ ...base, color: "var(--color-text-subtle)" }),
  singleValue: (base) => ({ ...base, color: "var(--color-text-primary)" }),
  indicatorSeparator: (base) => ({ ...base, backgroundColor: "var(--color-border-subtle)" }),
  dropdownIndicator: (base) => ({ ...base, color: "var(--color-text-muted)" }),
  clearIndicator: (base) => ({ ...base, color: "var(--color-text-muted)" }),
};

const YOLO_CATEGORY_VALUES = [
  "person",
  "bicycle",
  "car",
  "motorcycle",
  "airplane",
  "bus",
  "train",
  "truck",
  "boat",
  "traffic light",
  "fire hydrant",
  "stop sign",
  "parking meter",
  "bench",
  "bird",
  "cat",
  "dog",
  "horse",
  "sheep",
  "cow",
  "elephant",
  "bear",
  "zebra",
  "giraffe",
  "backpack",
  "umbrella",
  "handbag",
  "tie",
  "suitcase",
  "frisbee",
  "skis",
  "snowboard",
  "sports ball",
  "kite",
  "baseball bat",
  "baseball glove",
  "skateboard",
  "surfboard",
  "tennis racket",
  "bottle",
  "wine glass",
  "cup",
  "fork",
  "knife",
  "spoon",
  "bowl",
  "banana",
  "apple",
  "sandwich",
  "orange",
  "broccoli",
  "carrot",
  "hot dog",
  "pizza",
  "donut",
  "cake",
  "chair",
  "couch",
  "potted plant",
  "bed",
  "dining table",
  "toilet",
  "tv",
  "laptop",
  "mouse",
  "remote",
  "keyboard",
  "cell phone",
  "microwave",
  "oven",
  "toaster",
  "sink",
  "refrigerator",
  "book",
  "clock",
  "vase",
  "scissors",
  "teddy bear",
  "hair drier",
  "toothbrush",
];

export const YOLO_CATEGORY_OPTIONS: SelectOption[] = YOLO_CATEGORY_VALUES.map((value) => ({ value, label: value }));

type TranslateFn = (key: string, params?: Record<string, unknown>, fallback?: string) => string;

const ARTIFACT_SUGGESTION_DEFS: Array<{ value: string; labelKey: string; fallback: string }> = [
  { value: "best_frame", labelKey: "core.ui.pipelines.artifacts.best_frame", fallback: "Best frame" },
  { value: "segmented", labelKey: "core.ui.pipelines.artifacts.segmented", fallback: "Segmented" },
  { value: "treated", labelKey: "core.ui.pipelines.artifacts.treated", fallback: "Treated" },
  { value: "original", labelKey: "core.ui.pipelines.artifacts.original", fallback: "Original" },
  { value: "face", labelKey: "core.ui.pipelines.artifacts.face", fallback: "Face" },
  { value: "pose", labelKey: "core.ui.pipelines.artifacts.pose", fallback: "Pose" },
];

export function buildArtifactSuggestions(t: TranslateFn): SelectOption[] {
  return ARTIFACT_SUGGESTION_DEFS.map((item) => ({ value: item.value, label: t(item.labelKey, {}, item.fallback) }));
}

const WEEKDAY_DEFS: Array<{ value: string; labelKey: string; fallback: string }> = [
  { value: "mon", labelKey: "core.ui.pipelines.weekday.mon", fallback: "Mon" },
  { value: "tue", labelKey: "core.ui.pipelines.weekday.tue", fallback: "Tue" },
  { value: "wed", labelKey: "core.ui.pipelines.weekday.wed", fallback: "Wed" },
  { value: "thu", labelKey: "core.ui.pipelines.weekday.thu", fallback: "Thu" },
  { value: "fri", labelKey: "core.ui.pipelines.weekday.fri", fallback: "Fri" },
  { value: "sat", labelKey: "core.ui.pipelines.weekday.sat", fallback: "Sat" },
  { value: "sun", labelKey: "core.ui.pipelines.weekday.sun", fallback: "Sun" },
];

export function buildScheduleWeekdayOptions(t: TranslateFn): SelectOption[] {
  return WEEKDAY_DEFS.map((item) => ({ value: item.value, label: t(item.labelKey, {}, item.fallback) }));
}

export const HUMANIZE_ACRONYMS: Record<string, string> = {
  id: "ID",
  fps: "FPS",
  rtsp: "RTSP",
  url: "URL",
  jpeg: "JPEG",
  png: "PNG",
  yolo: "YOLO",
  api: "API",
  ui: "UI",
  sse: "SSE",
  ts: "TS",
};
